### ISSUE TITLE
ipad: tooltip appears empty, or is stuck at first position when scrubbing

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#908]
I first thought it's only the simulator, but encountered the problem also on a real device.

**Comment by blacktrash** [comment]
@nnarhinen - is the timeline tooltip _meant_ to show on touch devices and doesn't work, or is the hiding not complete, and it's just a matter of ruling e.g. `display: none` in the appropriate places?

**Comment by nnarhinen** [comment]
I don't think it's worth showing at all. (It would be under the finger anyway). Maybe we should just hide the tooltip on touch devices and come up with a working solution later on, if we see the need.

**Comment by blacktrash** [comment]
Personally I'm fine with not showing it on touch devices, I just wasn't sure how it was meant to be.

**Comment by nnarhinen** [comment]
Should be fixed on http://demos.dev94.flowplayer.us My iPad battery is dead, cannot test.

**Comment by blacktrash** [comment]
I can still see it. The generated code also looks wrong to me:
```css
.is-touch .flowplayer .fp-timeline:hover+.fp-timeline-tooltip{display:none}
```
should be:
```css
.is-touch.flowplayer .fp-timeline:hover+.fp-timeline-tooltip{display:none}
```
Sending fix.

**Comment by blacktrash** [comment]
My followup patch is tested ;-)
